version: '3.1'

services:
  mysqldb:
    image: mysql
    container_name: mysqlapp
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Test_google
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_PASSWORD: 123456

  app:
    build: ./
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://34.155.110.139:3306/Test_google
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"